sudo: required

cache:
  directories:
    - /home/travis/.rvm/

services:
  - docker

before_install:
  - docker build -t tests-runner:$TRAVIS_COMMIT .

script:
  - docker run tests-runner:$TRAVIS_COMMIT
